export const strings = {
  en: {
    'onboarding.language.title': 'Choose your language',
    'onboarding.language.subtitle': 'You can use Vienna Lost & Found in English or German.',
    'onboarding.language.english': 'English',
    'onboarding.language.german': 'Deutsch',
    'onboarding.language.error': 'Could not save the language. Please try again.',
    'onboarding.guest.title': 'Your guest pass',
    'onboarding.guest.subtitle': 'A name and email are enough to test the Vienna lost-and-found flow.',
    'onboarding.guest.nameLabel': 'Name',
    'onboarding.guest.namePlaceholder': 'Your name',
    'onboarding.guest.emailLabel': 'Email',
    'onboarding.guest.emailPlaceholder': 'you@example.com',
    'onboarding.guest.button': 'Start as guest',
    'onboarding.guest.nameError': 'Please enter your name.',
    'onboarding.guest.emailError': 'Please enter a valid email address.',
    'onboarding.guest.saveError': 'Could not finish onboarding. Please try again.',
    'home.lost.heading': 'I lost\nsomething.',
    'home.lost.hint': 'Report a loss — even without an exact address',
    'home.found.heading': 'I found\nsomething.',
    'home.found.hint': 'Mark a found item in under 30 seconds',
    'matching.itemFallback': 'Item',
    'matching.cityFallbackPlace': 'Vienna city center',
    'matching.backCta': 'Back',
    'possibleMatch.title': 'Possible match',
    'possibleMatch.eyebrow': 'Check first',
    'possibleMatch.body': 'A finder reported something similar. Please confirm whether this could be your item.',
    'possibleMatch.place': 'Found at',
    'possibleMatch.address': 'Address',
    'possibleMatch.foundAt': 'Reported',
    'possibleMatch.description': 'Description',
    'possibleMatch.descriptionFallback': 'The finder did not add a description.',
    'possibleMatch.photoCaption': "Finder's photo",
    'possibleMatch.photoMissing': 'No photo provided',
    'possibleMatch.confirmCta': 'This is my item',
    'possibleMatch.rejectCta': 'Not my item',
    'fundbox.map.title': 'Nearest Fundbox',
    'fundbox.map.recommended': 'Recommended',
    'fundbox.map.routeCta': 'Show route',
    'fundbox.map.allBoxes': 'All Fundboxes',
    'fundbox.map.loading': 'Finding the closest Fundbox…',
    'fundbox.map.error': 'Could not load Fundbox locations.',
    'fundbox.route.title': 'Route to Fundbox',
    'fundbox.route.distanceUnit': 'm',
    'fundbox.route.timeUnit': 'min',
    'fundbox.route.arrivedCta': 'I have arrived',
    'fundbox.matchRoute.title': 'Route to your item',
    'fundbox.matchRoute.pickedUpCta': 'I picked it up',
    'fundbox.dropoff.title': 'Drop off',
    'fundbox.dropoff.recapEyebrow': 'You are dropping off',
    'fundbox.dropoff.checkItem': 'Item placed in the box',
    'fundbox.dropoff.checkClosed': 'Box closed again',
    'fundbox.dropoff.confirmCta': 'Confirm drop-off',
    'fundbox.success.eyebrow': 'Thank you',
    'fundbox.success.hero': 'ALL SET',
    'fundbox.success.hint': 'The owner will be notified automatically.',
    'fundbox.success.codeLabel': 'Pickup code',
    'fundbox.success.codeHint': 'Share this code with the owner so they can claim the item.',
    'fundbox.success.home': 'Back to start',
    'fundbox.claim.title': 'Claim item',
    'fundbox.claim.eyebrow': 'Possible match',
    'fundbox.claim.foundAt': 'Dropped off',
    'fundbox.claim.codePrompt': 'Enter the pickup code from the finder',
    'fundbox.claim.confirmCta': 'Confirm claim',
    'fundbox.claim.successHero': 'MATCH CONFIRMED!',
    'fundbox.claim.successHint': 'Pick up your item at the Fundbox.',
    'loser.flow.title': 'Report loss',
    'loser.flow.editTitle': 'Edit report',
    'loser.category.title': 'What did you lose?',
    'loser.category.subtitle': 'Pick the closest match — you can describe the details later.',
    'loser.category.phone': 'Smartphone',
    'loser.category.keys': 'Keys',
    'loser.category.wallet': 'Wallet',
    'loser.category.umbrella': 'Umbrella',
    'loser.category.headphones': 'Headphones',
    'loser.category.glasses': 'Glasses',
    'loser.category.other': 'Something else',
    'loser.category.eyebrow': 'Category',
    'loser.category.cta': 'Continue',
    'loser.description.eyebrow': 'Description',
    'loser.description.optional': 'optional · helps matching',
    'loser.description.required': 'required for "Something else"',
    'loser.description.placeholder': 'e.g. black backpack with yellow tag',
    'loser.mode.title': 'Where did it happen?',
    'loser.mode.subtitle': 'Two ways to pin it down — even if your memory is fuzzy.',
    'loser.mode.map.title': 'On the map',
    'loser.mode.map.hint': 'Drop a pin or trace your route',
    'loser.mode.address.title': 'By address',
    'loser.mode.address.hint': 'Pick a district or search a street',
    'loser.tab.pin': 'Pin + radius',
    'loser.tab.route': 'Draw route',
    'loser.tab.steps': 'Step by step',
    'loser.tab.address': 'Exact address',
    'loser.pin.title': 'Approximate spot',
    'loser.pin.hint': 'Drag the marker. Adjust the radius below.',
    'loser.pin.radiusLabel': 'Search radius',
    'loser.pin.cta': 'Use this area',
    'loser.route.title': 'Your route',
    'loser.route.hint': 'Tap the map to add points along the way.',
    'loser.route.pointCount': 'points',
    'loser.route.undo': 'Undo',
    'loser.route.cta': 'Use this route',
    'loser.steps.title': 'Step by step',
    'loser.steps.pickBezirk': 'Pick a district',
    'loser.steps.pickStreet': 'Pick a street (optional)',
    'loser.steps.landmarkLabel': 'Landmark (optional)',
    'loser.steps.landmarkPlaceholder': 'e.g. Café Demel',
    'loser.steps.cta': 'Use this district',
    'loser.address.title': 'Search address',
    'loser.address.placeholder': 'Start typing a street…',
    'loser.address.noResults': 'No matches yet. Keep typing.',
    'loser.address.cta': 'Use this address',
    'loser.confirm.title': 'Ready to report?',
    'loser.confirm.categorySection': 'Category',
    'loser.confirm.locationSection': 'Location',
    'loser.confirm.notifySection': 'Notifications',
    'loser.confirm.pushLabel': 'Notify me on possible matches',
    'loser.confirm.pushHint': 'We will ping you when a finder reports something similar.',
    'loser.confirm.cta': 'Send report',
    'loser.confirm.saveError': 'Could not send the report. Please try again.',
    'loser.success.eyebrow': 'You are listed',
    'loser.success.hero': 'WE ARE LOOKING.',
    'loser.success.hint': 'You will hear from us as soon as something matches.',
    'loser.success.home': 'Back to start',
    'loser.location.pinSummary': 'Pin · {radius} m radius',
    'loser.location.routeSummary': 'Route · {count} points',
    'loser.location.stepsSummary': '{number}. Bezirk · {name}',
    'loser.location.addressSummary': 'Address',
    'activity.title': 'My items',
    'activity.tab.found': 'My found items',
    'activity.tab.lost': 'My lost items',
    'activity.headerButtonLabel': 'My found and lost items',
    'activity.found.wallet.category': 'Wallet',
    'activity.found.wallet.title': 'Brown wallet',
    'activity.found.wallet.location': 'U4 Schwedenplatz',
    'activity.found.wallet.date': 'Today, 14:20',
    'activity.found.wallet.status': 'Marked',
    'activity.found.keys.category': 'Keys',
    'activity.found.keys.title': 'Keychain with red strap',
    'activity.found.keys.location': 'Karlsplatz',
    'activity.found.keys.date': 'Yesterday, 18:05',
    'activity.found.keys.status': 'In Fundbox',
    'activity.found.phone.category': 'Phone',
    'activity.found.phone.title': 'iPhone with black case',
    'activity.found.phone.location': 'Fundbox Praterstern',
    'activity.found.phone.date': 'Last week',
    'activity.found.phone.status': 'Returned',
    'activity.lost.backpack.category': 'Backpack',
    'activity.lost.backpack.title': 'Black backpack',
    'activity.lost.backpack.location': 'Route: Donaukanal to Schwedenplatz',
    'activity.lost.backpack.date': 'Sat, 22:30',
    'activity.lost.backpack.status': 'Active',
    'activity.lost.backpack.matchStatus': 'Possible match',
    'activity.lost.backpack.matchDescription':
      'Black backpack with a laptop sleeve and a red water bottle in the side pocket.',
    'activity.lost.scarf.category': 'Clothing',
    'activity.lost.scarf.title': 'Green scarf',
    'activity.lost.scarf.location': 'Campus library',
    'activity.lost.scarf.date': 'Today, 11:45',
    'activity.lost.scarf.status': 'Active',
    'activity.lost.documents.category': 'Documents',
    'activity.lost.documents.title': 'Residence card',
    'activity.lost.documents.location': 'Wien Mitte',
    'activity.lost.documents.date': 'Mon, 09:10',
    'activity.lost.documents.status': 'Possible match',
    'activity.lost.documents.matchDescription':
      'Residence card and a student ID inside a beige folder.',
    'activity.lost.wallet.category': 'Wallet',
    'activity.lost.wallet.title': 'Black wallet',
    'activity.lost.wallet.location': 'Mariahilfer Strasse',
    'activity.lost.wallet.date': 'Last week',
    'activity.lost.wallet.status': 'Found',
    'activity.lost.bike.category': 'Bike',
    'activity.lost.bike.title': 'Blue city bike',
    'activity.lost.bike.location': 'Naschmarkt',
    'activity.lost.bike.date': 'Apr 28, 17:40',
    'activity.lost.bike.status': 'Closed',
    'activity.headerButtonText': 'History',
    'activity.detail.title': 'Item details',
    'activity.detail.close': 'Close',
    'activity.detail.type': 'Type',
    'activity.detail.foundType': 'Found item',
    'activity.detail.lostType': 'Lost item',
    'activity.detail.status': 'Status',
    'activity.detail.location': 'Location',
    'activity.detail.date': 'Date',
    'activity.detail.noNewsTitle': 'No news yet',
    'activity.detail.noNewsBody': 'This entry is active. Updates will appear here as soon as something changes.',
    'activity.detail.matchTitle': 'Possible matches',
    'activity.detail.matchBody': 'A matching report is ready to open.',
    'activity.detail.openMapMatch': 'Show route',
    'activity.detail.openFundboxMatch': 'Open Fundbox',
    'activity.detail.completedTitle': 'Completed entry',
    'activity.detail.completedBody': 'This case is no longer active. The details below stay available for your history.',
    'activity.edit.action': 'Edit report',
    'activity.edit.cardLabel': 'Edit this report',
    'finder.camera.title': 'Camera & Location',
    'finder.camera.gpsAuto': 'Location auto-detected',
    'finder.camera.gpsLoading': 'Detecting location…',
    'finder.camera.gpsManual': 'Set manually',
    'finder.camera.gpsNoPermission': 'No GPS access — tap to set manually',
    'finder.camera.noCameraPermission': 'Camera access required',
    'finder.camera.openSettings': 'Open Settings',
    'finder.camera.retry': 'Retry',
    'finder.camera.cta': 'Continue',
    'finder.camera.ctaHint': '→ CHOOSE ACTION',
    'finder.location.title': 'Set location',
    'finder.location.tabMap': 'Map',
    'finder.location.tabAddress': 'Address',
    'finder.location.pinHint': 'Tap the map to place a pin',
    'finder.location.cta': 'Use this location',
    'finder.location.addressPlaceholder': 'Enter street…',
    'finder.location.noResults': 'No matches yet. Keep typing.',
    'finder.choice.title': 'What now?',
    'finder.choice.leaveHeading': 'Leave it here\n& mark it.',
    'finder.choice.leaveHint': 'We mark the exact spot and notify the owner to pick it up there.',
    'finder.choice.fundboxHeading': 'Take it to\nFundbox.',
    'finder.choice.fundboxHint': 'Drop it in the nearest Fundbox — the owner is notified automatically.',
    'finder.choice.whatIsFundbox': 'What is a Fundbox?',
    'finder.choice.fundboxInfoTitle': 'What is a Fundbox?',
    'finder.choice.fundboxInfoBody':
      'A Fundbox is a secure public locker in Vienna for found items. Drop an item into the nearest box and it is locked safely. The owner is notified automatically and can collect it with a pickup code.',
    'finder.choice.fundboxInfoClose': 'Got it',
    'finder.success.eyebrow': 'Location saved',
    'finder.success.hero': 'THANK YOU!',
    'finder.success.hint': 'The found item has been reported.',
    'finder.success.home': 'Back to start',
  },
  de: {
    'onboarding.language.title': 'Sprache wählen',
    'onboarding.language.subtitle': 'Sie können Vienna Lost & Found auf Deutsch oder Englisch nutzen.',
    'onboarding.language.english': 'English',
    'onboarding.language.german': 'Deutsch',
    'onboarding.language.error': 'Die Sprache konnte nicht gespeichert werden. Bitte versuchen Sie es erneut.',
    'onboarding.guest.title': 'Ihr Gäste-Pass',
    'onboarding.guest.subtitle': 'Name und E-Mail reichen aus, um den Wiener Fundservice zu testen.',
    'onboarding.guest.nameLabel': 'Name',
    'onboarding.guest.namePlaceholder': 'Ihr Name',
    'onboarding.guest.emailLabel': 'E-Mail',
    'onboarding.guest.emailPlaceholder': 'sie@beispiel.at',
    'onboarding.guest.button': 'Als Gast starten',
    'onboarding.guest.nameError': 'Bitte geben Sie Ihren Namen ein.',
    'onboarding.guest.emailError': 'Bitte geben Sie eine gültige E-Mail-Adresse ein.',
    'onboarding.guest.saveError': 'Onboarding konnte nicht abgeschlossen werden. Bitte versuchen Sie es erneut.',
    'home.lost.heading': 'Ich habe etwas\nverloren.',
    'home.lost.hint': 'Verlust melden — auch ohne genaue Adresse',
    'home.found.heading': 'Ich habe etwas\ngefunden.',
    'home.found.hint': 'Fundort in unter 30 Sekunden markieren',
    'matching.itemFallback': 'Gegenstand',
    'matching.cityFallbackPlace': 'Wien Innenstadt',
    'matching.backCta': 'Zurück',
    'possibleMatch.title': 'Möglicher Treffer',
    'possibleMatch.eyebrow': 'Bitte prüfen',
    'possibleMatch.body': 'Ein Finder hat etwas Ähnliches gemeldet. Bitte bestätige zuerst, ob es dein Gegenstand sein könnte.',
    'possibleMatch.place': 'Gefunden bei',
    'possibleMatch.address': 'Adresse',
    'possibleMatch.foundAt': 'Gemeldet',
    'possibleMatch.description': 'Beschreibung',
    'possibleMatch.descriptionFallback': 'Der Finder hat keine Beschreibung hinzugefügt.',
    'possibleMatch.photoCaption': 'Foto des Finders',
    'possibleMatch.photoMissing': 'Kein Foto vorhanden',
    'possibleMatch.confirmCta': 'Das ist mein Gegenstand',
    'possibleMatch.rejectCta': 'Nicht mein Gegenstand',
    'fundbox.map.title': 'Nächste Fundbox',
    'fundbox.map.recommended': 'Empfohlen',
    'fundbox.map.routeCta': 'Route anzeigen',
    'fundbox.map.allBoxes': 'Alle Fundboxen',
    'fundbox.map.loading': 'Suche die nächste Fundbox…',
    'fundbox.map.error': 'Fundbox-Standorte konnten nicht geladen werden.',
    'fundbox.route.title': 'Zur Fundbox',
    'fundbox.route.distanceUnit': 'm',
    'fundbox.route.timeUnit': 'min',
    'fundbox.route.arrivedCta': 'Ich bin angekommen',
    'fundbox.matchRoute.title': 'Route zu deinem Gegenstand',
    'fundbox.matchRoute.pickedUpCta': 'Ich habe ihn abgeholt',
    'fundbox.dropoff.title': 'Ablegen',
    'fundbox.dropoff.recapEyebrow': 'Sie geben ab',
    'fundbox.dropoff.checkItem': 'Gegenstand in der Box abgelegt',
    'fundbox.dropoff.checkClosed': 'Box wieder geschlossen',
    'fundbox.dropoff.confirmCta': 'Abgabe bestätigen',
    'fundbox.success.eyebrow': 'Vielen Dank',
    'fundbox.success.hero': 'GESCHAFFT',
    'fundbox.success.hint': 'Der Eigentümer wird automatisch benachrichtigt.',
    'fundbox.success.codeLabel': 'Abholcode',
    'fundbox.success.codeHint': 'Teile diesen Code mit dem Eigentümer, damit er den Gegenstand abholen kann.',
    'fundbox.success.home': 'Zurück zum Start',
    'fundbox.claim.title': 'Anspruch erheben',
    'fundbox.claim.eyebrow': 'Möglicher Treffer',
    'fundbox.claim.foundAt': 'Abgegeben',
    'fundbox.claim.codePrompt': 'Geben Sie den Abholcode des Finders ein',
    'fundbox.claim.confirmCta': 'Anspruch bestätigen',
    'fundbox.claim.successHero': 'TREFFER BESTÄTIGT!',
    'fundbox.claim.successHint': 'Holen Sie Ihr Eigentum bei der Fundbox ab.',
    'loser.flow.title': 'Verlust melden',
    'loser.flow.editTitle': 'Meldung bearbeiten',
    'loser.category.title': 'Was hast du verloren?',
    'loser.category.subtitle': 'Wähle die passendste Kategorie — Details kommen später.',
    'loser.category.phone': 'Smartphone',
    'loser.category.keys': 'Schlüssel',
    'loser.category.wallet': 'Geldbörse',
    'loser.category.umbrella': 'Regenschirm',
    'loser.category.headphones': 'Kopfhörer',
    'loser.category.glasses': 'Brille',
    'loser.category.other': 'Sonstiges',
    'loser.category.eyebrow': 'Kategorie',
    'loser.category.cta': 'Weiter',
    'loser.description.eyebrow': 'Beschreibung',
    'loser.description.optional': 'optional · hilft beim Treffer',
    'loser.description.required': 'Pflichtfeld bei „Sonstiges"',
    'loser.description.placeholder': 'z. B. schwarzer Rucksack mit gelbem Anhänger',
    'loser.mode.title': 'Wo war es?',
    'loser.mode.subtitle': 'Zwei Wege — auch wenn die Erinnerung verschwommen ist.',
    'loser.mode.map.title': 'Auf der Karte',
    'loser.mode.map.hint': 'Pin setzen oder den Weg nachzeichnen',
    'loser.mode.address.title': 'Per Adresse',
    'loser.mode.address.hint': 'Bezirk wählen oder Straße suchen',
    'loser.tab.pin': 'Pin + Radius',
    'loser.tab.route': 'Route zeichnen',
    'loser.tab.steps': 'Schritt für Schritt',
    'loser.tab.address': 'Genaue Adresse',
    'loser.pin.title': 'Ungefährer Ort',
    'loser.pin.hint': 'Marker ziehen. Radius unten anpassen.',
    'loser.pin.radiusLabel': 'Suchradius',
    'loser.pin.cta': 'Diesen Bereich übernehmen',
    'loser.route.title': 'Dein Weg',
    'loser.route.hint': 'Tippe auf die Karte, um Punkte hinzuzufügen.',
    'loser.route.pointCount': 'Punkte',
    'loser.route.undo': 'Zurück',
    'loser.route.cta': 'Diese Route übernehmen',
    'loser.steps.title': 'Schritt für Schritt',
    'loser.steps.pickBezirk': 'Bezirk wählen',
    'loser.steps.pickStreet': 'Straße wählen (optional)',
    'loser.steps.landmarkLabel': 'Ort in der Nähe (optional)',
    'loser.steps.landmarkPlaceholder': 'z. B. Café Demel',
    'loser.steps.cta': 'Diesen Bezirk übernehmen',
    'loser.address.title': 'Adresse suchen',
    'loser.address.placeholder': 'Straßenname eintippen…',
    'loser.address.noResults': 'Noch keine Treffer. Weiter tippen.',
    'loser.address.cta': 'Diese Adresse übernehmen',
    'loser.confirm.title': 'Bereit zur Meldung?',
    'loser.confirm.categorySection': 'Kategorie',
    'loser.confirm.locationSection': 'Ort',
    'loser.confirm.notifySection': 'Benachrichtigung',
    'loser.confirm.pushLabel': 'Push bei möglichem Treffer',
    'loser.confirm.pushHint': 'Wir melden uns, sobald jemand etwas Passendes findet.',
    'loser.confirm.cta': 'Melden',
    'loser.confirm.saveError': 'Meldung konnte nicht gesendet werden. Bitte erneut versuchen.',
    'loser.success.eyebrow': 'Eingetragen',
    'loser.success.hero': 'WIR SUCHEN MIT.',
    'loser.success.hint': 'Du hörst von uns, sobald etwas passendes auftaucht.',
    'loser.success.home': 'Zurück zum Start',
    'loser.location.pinSummary': 'Pin · {radius} m Radius',
    'loser.location.routeSummary': 'Route · {count} Punkte',
    'loser.location.stepsSummary': '{number}. Bezirk · {name}',
    'loser.location.addressSummary': 'Adresse',
    'activity.title': 'Meine Sachen',
    'activity.tab.found': 'Meine Funde',
    'activity.tab.lost': 'Meine Verluste',
    'activity.headerButtonLabel': 'Meine Funde und Verluste',
    'activity.found.wallet.category': 'Geldbörse',
    'activity.found.wallet.title': 'Braune Geldbörse',
    'activity.found.wallet.location': 'U4 Schwedenplatz',
    'activity.found.wallet.date': 'Heute, 14:20',
    'activity.found.wallet.status': 'Markiert',
    'activity.found.keys.category': 'Schlüssel',
    'activity.found.keys.title': 'Schlüsselbund mit rotem Band',
    'activity.found.keys.location': 'Karlsplatz',
    'activity.found.keys.date': 'Gestern, 18:05',
    'activity.found.keys.status': 'In Fundbox',
    'activity.found.phone.category': 'Handy',
    'activity.found.phone.title': 'iPhone mit schwarzer Hülle',
    'activity.found.phone.location': 'Fundbox Praterstern',
    'activity.found.phone.date': 'Letzte Woche',
    'activity.found.phone.status': 'Zurückgegeben',
    'activity.lost.backpack.category': 'Rucksack',
    'activity.lost.backpack.title': 'Schwarzer Rucksack',
    'activity.lost.backpack.location': 'Route: Donaukanal nach Schwedenplatz',
    'activity.lost.backpack.date': 'Sa, 22:30',
    'activity.lost.backpack.status': 'Aktiv',
    'activity.lost.backpack.matchStatus': 'Möglicher Treffer',
    'activity.lost.backpack.matchDescription':
      'Schwarzer Rucksack mit Laptopfach und einer roten Trinkflasche in der Seitentasche.',
    'activity.lost.scarf.category': 'Kleidung',
    'activity.lost.scarf.title': 'Grüner Schal',
    'activity.lost.scarf.location': 'Campus-Bibliothek',
    'activity.lost.scarf.date': 'Heute, 11:45',
    'activity.lost.scarf.status': 'Aktiv',
    'activity.lost.documents.category': 'Dokumente',
    'activity.lost.documents.title': 'Aufenthaltskarte',
    'activity.lost.documents.location': 'Wien Mitte',
    'activity.lost.documents.date': 'Mo, 09:10',
    'activity.lost.documents.status': 'Möglicher Treffer',
    'activity.lost.documents.matchDescription':
      'Aufenthaltskarte und ein Studentenausweis in einer beigen Mappe.',
    'activity.lost.wallet.category': 'Geldbörse',
    'activity.lost.wallet.title': 'Schwarze Geldbörse',
    'activity.lost.wallet.location': 'Mariahilfer Straße',
    'activity.lost.wallet.date': 'Letzte Woche',
    'activity.lost.wallet.status': 'Gefunden',
    'activity.lost.bike.category': 'Fahrrad',
    'activity.lost.bike.title': 'Blaues Citybike',
    'activity.lost.bike.location': 'Naschmarkt',
    'activity.lost.bike.date': '28. Apr, 17:40',
    'activity.lost.bike.status': 'Abgeschlossen',
    'activity.headerButtonText': 'Verlauf',
    'activity.detail.title': 'Details',
    'activity.detail.close': 'Schließen',
    'activity.detail.type': 'Typ',
    'activity.detail.foundType': 'Fund',
    'activity.detail.lostType': 'Verlust',
    'activity.detail.status': 'Status',
    'activity.detail.location': 'Ort',
    'activity.detail.date': 'Datum',
    'activity.detail.noNewsTitle': 'Keine Neuigkeiten',
    'activity.detail.noNewsBody': 'Dieser Eintrag ist aktiv. Updates erscheinen hier, sobald sich etwas ändert.',
    'activity.detail.matchTitle': 'Mögliche Treffer',
    'activity.detail.matchBody': 'Ein passender Fund ist bereit.',
    'activity.detail.openMapMatch': 'Route anzeigen',
    'activity.detail.openFundboxMatch': 'Fundbox öffnen',
    'activity.detail.completedTitle': 'Abgeschlossener Eintrag',
    'activity.detail.completedBody': 'Dieser Fall ist nicht mehr aktiv. Die Details bleiben in deinem Verlauf sichtbar.',
    'activity.edit.action': 'Meldung bearbeiten',
    'activity.edit.cardLabel': 'Diese Meldung bearbeiten',
    'finder.camera.title': 'Kamera & Standort',
    'finder.camera.gpsAuto': 'Standort automatisch erfasst',
    'finder.camera.gpsLoading': 'Standort wird erfasst…',
    'finder.camera.gpsManual': 'Manuell gesetzt',
    'finder.camera.gpsNoPermission': 'Kein GPS-Zugriff — tippe zum manuellen Eingeben',
    'finder.camera.noCameraPermission': 'Kamera-Zugriff erforderlich',
    'finder.camera.openSettings': 'Einstellungen öffnen',
    'finder.camera.retry': 'Erneut versuchen',
    'finder.camera.cta': 'Weiter',
    'finder.camera.ctaHint': '→ AKTION WÄHLEN',
    'finder.location.title': 'Standort wählen',
    'finder.location.tabMap': 'Karte',
    'finder.location.tabAddress': 'Adresse',
    'finder.location.pinHint': 'Tippe auf die Karte',
    'finder.location.cta': 'Diesen Ort nehmen',
    'finder.location.addressPlaceholder': 'Straße eingeben…',
    'finder.location.noResults': 'Noch keine Treffer. Weiter tippen.',
    'finder.choice.title': 'Was tun?',
    'finder.choice.leaveHeading': 'Liegen lassen\n& markieren.',
    'finder.choice.leaveHint': 'Wir markieren die genaue Stelle und benachrichtigen den Besitzer.',
    'finder.choice.fundboxHeading': 'Zur Fundbox\nbringen.',
    'finder.choice.fundboxHint': 'In der nächsten Fundbox abgeben — der Besitzer wird benachrichtigt.',
    'finder.choice.whatIsFundbox': 'Was ist eine Fundbox?',
    'finder.choice.fundboxInfoTitle': 'Was ist eine Fundbox?',
    'finder.choice.fundboxInfoBody':
      'Eine Fundbox ist ein sicheres öffentliches Schließfach in Wien für Fundsachen. Lege einen Gegenstand in die nächste Box, und er wird sicher verschlossen. Der Besitzer wird automatisch benachrichtigt und kann ihn mit einem Abholcode abholen.',
    'finder.choice.fundboxInfoClose': 'Verstanden',
    'finder.success.eyebrow': 'Fundort gespeichert',
    'finder.success.hero': 'DANKE!',
    'finder.success.hint': 'Der Fundort ist gemeldet.',
    'finder.success.home': 'Zurück zum Start',
  },
} as const;

export type Language = keyof typeof strings;
export type StringKey = keyof typeof strings.en;
