export const strings = {
  en: {
    'onboarding.language.title': 'Choose your language',
    'onboarding.language.subtitle': 'You can use Vienna Lost & Found in English or German.',
    'onboarding.language.english': 'English',
    'onboarding.language.german': 'Deutsch',
    'onboarding.language.error': 'Could not save the language. Please try again.',
    'onboarding.guest.title': 'Your guest pass',
    'onboarding.guest.subtitle': 'A name and email are enough to test the Vienna lost-and-found flow.',
    'onboarding.guest.nameLabel': 'Name',
    'onboarding.guest.namePlaceholder': 'Your name',
    'onboarding.guest.emailLabel': 'Email',
    'onboarding.guest.emailPlaceholder': 'you@example.com',
    'onboarding.guest.button': 'Start as guest',
    'onboarding.guest.nameError': 'Please enter your name.',
    'onboarding.guest.emailError': 'Please enter a valid email address.',
    'onboarding.guest.saveError': 'Could not finish onboarding. Please try again.',
    'fundbox.map.title': 'Nearest Fundbox',
    'fundbox.map.recommended': 'Recommended',
    'fundbox.map.routeCta': 'Show route',
    'fundbox.map.allBoxes': 'All Fundboxes',
    'fundbox.map.loading': 'Finding the closest Fundbox…',
    'fundbox.map.error': 'Could not load Fundbox locations.',
    'fundbox.route.title': 'Route to Fundbox',
    'fundbox.route.distanceUnit': 'm',
    'fundbox.route.timeUnit': 'min',
    'fundbox.route.arrivedCta': 'I have arrived',
    'fundbox.dropoff.title': 'Drop off',
    'fundbox.dropoff.recapEyebrow': 'You are dropping off',
    'fundbox.dropoff.checkItem': 'Item placed in the box',
    'fundbox.dropoff.checkClosed': 'Box closed again',
    'fundbox.dropoff.confirmCta': 'Confirm drop-off',
    'fundbox.code.title': 'Done',
    'fundbox.code.hero': 'ALL SET',
    'fundbox.code.eyebrow': 'Pickup code',
    'fundbox.code.hint': 'Keep this code — the owner needs it to pick up the item.',
    'fundbox.code.copyCta': 'Copy code',
    'fundbox.code.copied': 'Copied',
    'fundbox.code.homeCta': 'Back to start',
    'fundbox.claim.title': 'Claim item',
    'fundbox.claim.eyebrow': 'Possible match',
    'fundbox.claim.foundAt': 'Dropped off',
    'fundbox.claim.codePrompt': 'Enter the pickup code from the finder',
    'fundbox.claim.confirmCta': 'Confirm claim',
    'fundbox.claim.successHero': 'MATCH CONFIRMED!',
    'fundbox.claim.successHint': 'Pick up your item at the Fundbox.',
  },
  de: {
    'onboarding.language.title': 'Sprache wählen',
    'onboarding.language.subtitle': 'Sie können Vienna Lost & Found auf Deutsch oder Englisch nutzen.',
    'onboarding.language.english': 'English',
    'onboarding.language.german': 'Deutsch',
    'onboarding.language.error': 'Die Sprache konnte nicht gespeichert werden. Bitte versuchen Sie es erneut.',
    'onboarding.guest.title': 'Ihr Gäste-Pass',
    'onboarding.guest.subtitle': 'Name und E-Mail reichen aus, um den Wiener Fundservice zu testen.',
    'onboarding.guest.nameLabel': 'Name',
    'onboarding.guest.namePlaceholder': 'Ihr Name',
    'onboarding.guest.emailLabel': 'E-Mail',
    'onboarding.guest.emailPlaceholder': 'sie@beispiel.at',
    'onboarding.guest.button': 'Als Gast starten',
    'onboarding.guest.nameError': 'Bitte geben Sie Ihren Namen ein.',
    'onboarding.guest.emailError': 'Bitte geben Sie eine gültige E-Mail-Adresse ein.',
    'onboarding.guest.saveError': 'Onboarding konnte nicht abgeschlossen werden. Bitte versuchen Sie es erneut.',
    'fundbox.map.title': 'Nächste Fundbox',
    'fundbox.map.recommended': 'Empfohlen',
    'fundbox.map.routeCta': 'Route anzeigen',
    'fundbox.map.allBoxes': 'Alle Fundboxen',
    'fundbox.map.loading': 'Suche die nächste Fundbox…',
    'fundbox.map.error': 'Fundbox-Standorte konnten nicht geladen werden.',
    'fundbox.route.title': 'Zur Fundbox',
    'fundbox.route.distanceUnit': 'm',
    'fundbox.route.timeUnit': 'min',
    'fundbox.route.arrivedCta': 'Ich bin angekommen',
    'fundbox.dropoff.title': 'Ablegen',
    'fundbox.dropoff.recapEyebrow': 'Sie geben ab',
    'fundbox.dropoff.checkItem': 'Gegenstand in der Box abgelegt',
    'fundbox.dropoff.checkClosed': 'Box wieder geschlossen',
    'fundbox.dropoff.confirmCta': 'Abgabe bestätigen',
    'fundbox.code.title': 'Erledigt',
    'fundbox.code.hero': 'GESCHAFFT',
    'fundbox.code.eyebrow': 'Abholcode',
    'fundbox.code.hint': 'Code aufbewahren — der Eigentümer braucht ihn zur Abholung.',
    'fundbox.code.copyCta': 'Code kopieren',
    'fundbox.code.copied': 'Kopiert',
    'fundbox.code.homeCta': 'Zur Startseite',
    'fundbox.claim.title': 'Anspruch erheben',
    'fundbox.claim.eyebrow': 'Möglicher Treffer',
    'fundbox.claim.foundAt': 'Abgegeben',
    'fundbox.claim.codePrompt': 'Geben Sie den Abholcode des Finders ein',
    'fundbox.claim.confirmCta': 'Anspruch bestätigen',
    'fundbox.claim.successHero': 'TREFFER BESTÄTIGT!',
    'fundbox.claim.successHint': 'Holen Sie Ihr Eigentum bei der Fundbox ab.',
  },
} as const;

export type Language = keyof typeof strings;
export type StringKey = keyof typeof strings.en;
