export const strings = {
  en: {
    'onboarding.language.title': 'Choose your language',
    'onboarding.language.subtitle': 'You can use Vienna Lost & Found in English or German.',
    'onboarding.language.english': 'English',
    'onboarding.language.german': 'Deutsch',
    'onboarding.language.error': 'Could not save the language. Please try again.',
    'onboarding.guest.title': 'Your guest pass',
    'onboarding.guest.subtitle': 'A name and email are enough to test the Vienna lost-and-found flow.',
    'onboarding.guest.nameLabel': 'Name',
    'onboarding.guest.namePlaceholder': 'Your name',
    'onboarding.guest.emailLabel': 'Email',
    'onboarding.guest.emailPlaceholder': 'you@example.com',
    'onboarding.guest.button': 'Start as guest',
    'onboarding.guest.nameError': 'Please enter your name.',
    'onboarding.guest.emailError': 'Please enter a valid email address.',
    'onboarding.guest.saveError': 'Could not finish onboarding. Please try again.',
    'fundbox.map.title': 'Nearest Fundbox',
    'fundbox.map.recommended': 'Recommended',
    'fundbox.map.routeCta': 'Show route',
    'fundbox.map.allBoxes': 'All Fundboxes',
    'fundbox.map.loading': 'Finding the closest Fundbox…',
    'fundbox.map.error': 'Could not load Fundbox locations.',
    'fundbox.route.title': 'Route to Fundbox',
    'fundbox.route.distanceUnit': 'm',
    'fundbox.route.timeUnit': 'min',
    'fundbox.route.arrivedCta': 'I have arrived',
    'fundbox.dropoff.title': 'Drop off',
    'fundbox.dropoff.recapEyebrow': 'You are dropping off',
    'fundbox.dropoff.checkItem': 'Item placed in the box',
    'fundbox.dropoff.checkClosed': 'Box closed again',
    'fundbox.dropoff.confirmCta': 'Confirm drop-off',
    'fundbox.success.eyebrow': 'Thank you',
    'fundbox.success.hero': 'ALL SET',
    'fundbox.success.hint': 'The owner will be notified automatically.',
    'fundbox.claim.title': 'Claim item',
    'fundbox.claim.eyebrow': 'Possible match',
    'fundbox.claim.foundAt': 'Dropped off',
    'fundbox.claim.codePrompt': 'Enter the pickup code from the finder',
    'fundbox.claim.confirmCta': 'Confirm claim',
    'fundbox.claim.successHero': 'MATCH CONFIRMED!',
    'fundbox.claim.successHint': 'Pick up your item at the Fundbox.',
    'loser.category.title': 'What did you lose?',
    'loser.category.subtitle': 'Pick the closest match — you can describe the details later.',
    'loser.category.backpack': 'Backpack',
    'loser.category.keys': 'Keys',
    'loser.category.wallet': 'Wallet',
    'loser.category.phone': 'Phone',
    'loser.category.documents': 'Documents',
    'loser.category.bicycle': 'Bicycle',
    'loser.category.other': 'Something else',
    'loser.mode.title': 'Where did it happen?',
    'loser.mode.subtitle': 'Two ways to pin it down — even if your memory is fuzzy.',
    'loser.mode.map.title': 'On the map',
    'loser.mode.map.hint': 'Drop a pin or trace your route',
    'loser.mode.address.title': 'By address',
    'loser.mode.address.hint': 'Pick a district or search a street',
    'loser.tab.pin': 'Pin + radius',
    'loser.tab.route': 'Draw route',
    'loser.tab.steps': 'Step by step',
    'loser.tab.address': 'Exact address',
    'loser.pin.title': 'Approximate spot',
    'loser.pin.hint': 'Drag the marker. Adjust the radius below.',
    'loser.pin.radiusLabel': 'Search radius',
    'loser.pin.cta': 'Use this area',
    'loser.route.title': 'Your route',
    'loser.route.hint': 'Tap the map to add points along the way.',
    'loser.route.pointCount': 'points',
    'loser.route.undo': 'Undo',
    'loser.route.clear': 'Clear',
    'loser.route.cta': 'Use this route',
    'loser.route.empty': 'Add at least two points to continue.',
    'loser.steps.title': 'Step by step',
    'loser.steps.pickBezirk': 'Pick a district',
    'loser.steps.pickStreet': 'Pick a street (optional)',
    'loser.steps.landmarkLabel': 'Landmark (optional)',
    'loser.steps.landmarkPlaceholder': 'e.g. Café Demel',
    'loser.steps.cta': 'Use this district',
    'loser.address.title': 'Search address',
    'loser.address.placeholder': 'Start typing a street…',
    'loser.address.noResults': 'No matches yet. Keep typing.',
    'loser.address.cta': 'Use this address',
    'loser.confirm.title': 'Ready to report?',
    'loser.confirm.categorySection': 'Category',
    'loser.confirm.locationSection': 'Location',
    'loser.confirm.notifySection': 'Notifications',
    'loser.confirm.pushLabel': 'Notify me on possible matches',
    'loser.confirm.pushHint': 'We will ping you when a finder reports something similar.',
    'loser.confirm.cta': 'Send report',
    'loser.confirm.saveError': 'Could not send the report. Please try again.',
    'loser.success.eyebrow': 'You are listed',
    'loser.success.hero': 'WE ARE LOOKING.',
    'loser.success.hint': 'You will hear from us as soon as something matches.',
    'loser.success.home': 'Back to start',
    'loser.location.pinSummary': 'Pin · {radius} m radius',
    'loser.location.routeSummary': 'Route · {count} points',
    'loser.location.stepsSummary': '{number}. Bezirk · {name}',
    'loser.location.addressSummary': 'Address',
  },
  de: {
    'onboarding.language.title': 'Sprache wählen',
    'onboarding.language.subtitle': 'Sie können Vienna Lost & Found auf Deutsch oder Englisch nutzen.',
    'onboarding.language.english': 'English',
    'onboarding.language.german': 'Deutsch',
    'onboarding.language.error': 'Die Sprache konnte nicht gespeichert werden. Bitte versuchen Sie es erneut.',
    'onboarding.guest.title': 'Ihr Gäste-Pass',
    'onboarding.guest.subtitle': 'Name und E-Mail reichen aus, um den Wiener Fundservice zu testen.',
    'onboarding.guest.nameLabel': 'Name',
    'onboarding.guest.namePlaceholder': 'Ihr Name',
    'onboarding.guest.emailLabel': 'E-Mail',
    'onboarding.guest.emailPlaceholder': 'sie@beispiel.at',
    'onboarding.guest.button': 'Als Gast starten',
    'onboarding.guest.nameError': 'Bitte geben Sie Ihren Namen ein.',
    'onboarding.guest.emailError': 'Bitte geben Sie eine gültige E-Mail-Adresse ein.',
    'onboarding.guest.saveError': 'Onboarding konnte nicht abgeschlossen werden. Bitte versuchen Sie es erneut.',
    'fundbox.map.title': 'Nächste Fundbox',
    'fundbox.map.recommended': 'Empfohlen',
    'fundbox.map.routeCta': 'Route anzeigen',
    'fundbox.map.allBoxes': 'Alle Fundboxen',
    'fundbox.map.loading': 'Suche die nächste Fundbox…',
    'fundbox.map.error': 'Fundbox-Standorte konnten nicht geladen werden.',
    'fundbox.route.title': 'Zur Fundbox',
    'fundbox.route.distanceUnit': 'm',
    'fundbox.route.timeUnit': 'min',
    'fundbox.route.arrivedCta': 'Ich bin angekommen',
    'fundbox.dropoff.title': 'Ablegen',
    'fundbox.dropoff.recapEyebrow': 'Sie geben ab',
    'fundbox.dropoff.checkItem': 'Gegenstand in der Box abgelegt',
    'fundbox.dropoff.checkClosed': 'Box wieder geschlossen',
    'fundbox.dropoff.confirmCta': 'Abgabe bestätigen',
    'fundbox.success.eyebrow': 'Vielen Dank',
    'fundbox.success.hero': 'GESCHAFFT',
    'fundbox.success.hint': 'Der Eigentümer wird automatisch benachrichtigt.',
    'fundbox.claim.title': 'Anspruch erheben',
    'fundbox.claim.eyebrow': 'Möglicher Treffer',
    'fundbox.claim.foundAt': 'Abgegeben',
    'fundbox.claim.codePrompt': 'Geben Sie den Abholcode des Finders ein',
    'fundbox.claim.confirmCta': 'Anspruch bestätigen',
    'fundbox.claim.successHero': 'TREFFER BESTÄTIGT!',
    'fundbox.claim.successHint': 'Holen Sie Ihr Eigentum bei der Fundbox ab.',
    'loser.category.title': 'Was hast du verloren?',
    'loser.category.subtitle': 'Wähle die passendste Kategorie — Details kommen später.',
    'loser.category.backpack': 'Rucksack',
    'loser.category.keys': 'Schlüssel',
    'loser.category.wallet': 'Geldbörse',
    'loser.category.phone': 'Handy',
    'loser.category.documents': 'Dokumente',
    'loser.category.bicycle': 'Fahrrad',
    'loser.category.other': 'Sonstiges',
    'loser.mode.title': 'Wo war es?',
    'loser.mode.subtitle': 'Zwei Wege — auch wenn die Erinnerung verschwommen ist.',
    'loser.mode.map.title': 'Auf der Karte',
    'loser.mode.map.hint': 'Pin setzen oder den Weg nachzeichnen',
    'loser.mode.address.title': 'Per Adresse',
    'loser.mode.address.hint': 'Bezirk wählen oder Straße suchen',
    'loser.tab.pin': 'Pin + Radius',
    'loser.tab.route': 'Route zeichnen',
    'loser.tab.steps': 'Schritt für Schritt',
    'loser.tab.address': 'Genaue Adresse',
    'loser.pin.title': 'Ungefährer Ort',
    'loser.pin.hint': 'Marker ziehen. Radius unten anpassen.',
    'loser.pin.radiusLabel': 'Suchradius',
    'loser.pin.cta': 'Diesen Bereich übernehmen',
    'loser.route.title': 'Dein Weg',
    'loser.route.hint': 'Tippe auf die Karte, um Punkte hinzuzufügen.',
    'loser.route.pointCount': 'Punkte',
    'loser.route.undo': 'Zurück',
    'loser.route.clear': 'Zurücksetzen',
    'loser.route.cta': 'Diese Route übernehmen',
    'loser.route.empty': 'Mindestens zwei Punkte hinzufügen.',
    'loser.steps.title': 'Schritt für Schritt',
    'loser.steps.pickBezirk': 'Bezirk wählen',
    'loser.steps.pickStreet': 'Straße wählen (optional)',
    'loser.steps.landmarkLabel': 'Ort in der Nähe (optional)',
    'loser.steps.landmarkPlaceholder': 'z. B. Café Demel',
    'loser.steps.cta': 'Diesen Bezirk übernehmen',
    'loser.address.title': 'Adresse suchen',
    'loser.address.placeholder': 'Straßenname eintippen…',
    'loser.address.noResults': 'Noch keine Treffer. Weiter tippen.',
    'loser.address.cta': 'Diese Adresse übernehmen',
    'loser.confirm.title': 'Bereit zur Meldung?',
    'loser.confirm.categorySection': 'Kategorie',
    'loser.confirm.locationSection': 'Ort',
    'loser.confirm.notifySection': 'Benachrichtigung',
    'loser.confirm.pushLabel': 'Push bei möglichem Treffer',
    'loser.confirm.pushHint': 'Wir melden uns, sobald jemand etwas Passendes findet.',
    'loser.confirm.cta': 'Melden',
    'loser.confirm.saveError': 'Meldung konnte nicht gesendet werden. Bitte erneut versuchen.',
    'loser.success.eyebrow': 'Eingetragen',
    'loser.success.hero': 'WIR SUCHEN MIT.',
    'loser.success.hint': 'Du hörst von uns, sobald etwas passendes auftaucht.',
    'loser.success.home': 'Zurück zum Start',
    'loser.location.pinSummary': 'Pin · {radius} m Radius',
    'loser.location.routeSummary': 'Route · {count} Punkte',
    'loser.location.stepsSummary': '{number}. Bezirk · {name}',
    'loser.location.addressSummary': 'Adresse',
  },
} as const;

export type Language = keyof typeof strings;
export type StringKey = keyof typeof strings.en;
